debian: Change system user name to _yenma

diff --git a/debian/yenma.postrm b/debian/yenma.postrm
--- a/debian/yenma.postrm
+++ b/debian/yenma.postrm
@@ -1,12 +1,12 @@
 #!/bin/sh
 set -e
 
-if [ purge = "$1" ]; then
-   if [ -x "$(command -v deluser)" ]; then
-     deluser --quiet --system yenma
-  else
-     echo >&2 "not removing yenma system account because deluser command was not found"
-  fi
+if [ "$1" = purge ]; then
+    if [ -x "$(command -v deluser)" ]; then
+        deluser --system _yenma
+    else
+        echo >&2 "not removing yenma system account because deluser command was not found"
+    fi
 fi
 
 #DEBHELPER#
